DROP TABLE ITEMS IF EXISTS;

CREATE TABLE ITEMS (
  ID             VARCHAR(25) PRIMARY KEY,
  NAME           VARCHAR(100),
  CATEGORY       VARCHAR(50),
  COLOR          VARCHAR(40),
  SIZE           VARCHAR(10),
  QUANTITY       BIGINT,
  ARCHIVED       BOOLEAN
);

DROP TABLE EMPLOYEES IF EXISTS;

CREATE TABLE EMPLOYEES (
ID          VARCHAR(25) PRIMARY KEY,
NAME        VARCHAR(100),
SURNAME     VARCHAR(100)
);
