INSERT INTO ITEMS VALUES (1, 'Red Lace Midi', 'Dress', 'Red', 'M', 15, false);
INSERT INTO ITEMS VALUES (2, 'Raw Fit And Flare', 'Dress', 'Black', 'XL', 1, false);
INSERT INTO ITEMS VALUES (3, 'Molly Print', 'Dress', 'Green', 'S', 98, false);
INSERT INTO ITEMS VALUES (4, 'Navy Wrap Top', 'Shirt', 'Blue', 'XL', 23, false);
INSERT INTO ITEMS VALUES (5, 'Navy Trailing Floral', 'Shirt', 'Purple', 'XXL', 0, false);
INSERT INTO ITEMS VALUES (6, 'Ivory Songbird Print', 'Shirt', 'Grey', 'XL', 10, false);
INSERT INTO ITEMS VALUES (7, 'Black Woven Mix Tee', 'Tshirt', 'Black', 'L', 15, false);
INSERT INTO ITEMS VALUES (8, 'Yellow Ruffle Tee', 'Tshirt', 'Yellow', 'M', 43, false);
INSERT INTO ITEMS VALUES (9, 'Navy Sweetpea Ruffle Tee', 'Tshirt', 'Red', 'M', 113, false);
INSERT INTO ITEMS VALUES (10, 'Black Ponte', 'Trousers', 'Black', 'S', 45, false);
INSERT INTO ITEMS VALUES (11, 'Black Crepe Peg', 'Trousers', 'Black', 'L', 4, false);
INSERT INTO ITEMS VALUES (12, 'Soft Pleat Culotte', 'Trousers', 'Orange', 'XXXL', 42, false);
INSERT INTO ITEMS VALUES (13, 'Black Coated Skinny', 'Jeans', 'Black', 'XL', 89, false);
INSERT INTO ITEMS VALUES (14, 'Dark Wash Zip Front Wide Leg ', 'Jeans', 'Blue', 'M', 51, false);
INSERT INTO ITEMS VALUES (15, 'Black Coated Biker Jean', 'Jeans', 'Black', 'S', 5, false);
